FROM elasticsearch:7.17.26@sha256:340f15d5e07488e6bddc60e90690cab1288ffbccb4d20841fa282a7b6501fe51

RUN elasticsearch-plugin install analysis-icu && \
    elasticsearch-plugin install analysis-kuromoji
