FROM elasticsearch:9.2.1@sha256:872127ae799a4bb8a9c1a9b112d1670a27e2c31815a3965bb455c2b21e31b0f9

RUN elasticsearch-plugin install analysis-icu && \
    elasticsearch-plugin install analysis-kuromoji
